# Generated by Django 5.0.2 on 2024-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('opcion1', models.CharField(max_length=255)),
                ('opcion2', models.CharField(max_length=255)),
                ('opcion3', models.CharField(max_length=255)),
                ('opcion4', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
            ],
        ),
    ]
